{6500}{}{Mutant}
{6600}{}{Average Hobo}
{6700}{}{Strong Hobo}
{6800}{filename.test}{Strong Hobo}
{6900}{}{Dude}
{7000}{}{Weak Melee Guard}
{7100}{}{Weak Gun Guard}
{7200}{}{Weak Gun Guard}

# FIXME: invalid messages in CMBATAI2.MSG
#{32020}{}{Ow, my arm!
#{1382{}{My eyes, bitch!}

{7300}{}{Repair Bot}
{7400}{}{Repair Bot Mark II}
{7500}{}{Robobrain}
{7600}{}{Floating Eye Bot}
{7700}{}{Sentry Bot}
{7800}{}{Sentry Bot Mark II}